### ISSUE TITLE
Implement ResNet for gotorch

### ISSUE THREAD

**Issue by shendiaomo** [wangkuiyi/gotorch#121]
Examples in C++ and Python are in https://github.com/pytorch/vision/tree/master/torchvision/csrc/models and https://github.com/pytorch/vision/tree/master/torchvision/models
Prerequisites:
1. Wrap`torch::adaptive_avg_pool2d` in libtorch
2. Wrap `torch::max_pool2d` in libtorch
3. Wrap `torch::nn::functional::group_norm` in libtorch (the C++ version of resnet doesn't use `group_norm` at all, the python version use nn.GroupNorm only in a conditional statement)

**Comment by QiJune** [comment]
The imagenet training script reference: https://github.com/pytorch/examples/blob/master/imagenet/main.py

**Comment by wangkuiyi** [comment]
Fixed by https://github.com/wangkuiyi/gotorch/pull/317 and many earlier PRs.
