### ISSUE TITLE
Transformers required by ImageNet training example

### ISSUE THREAD

**Issue by Yancey1989** [wangkuiyi/gotorch#147]
To process the ImageNet dataset, we need
- [x] `ImageNetDataset` to load ImageNet images with `.tar.gz` file.
- [x] convert  HWC to CHW format

and the following transform functions:
- [x] Transofrms framework #196 
- [x] RandomResizedCrop: #197
- [x] RandomHorizontalFlip: #200
- [x] ToTensor #187 
- [x] Normalizer: #213
- [x] Resize: https://godoc.org/github.com/disintegration/imaging#Resize
- [x] CenterCrop: #203
-

**Comment by wangkuiyi** [comment]
The example training program that uses the above transformers

https://github.com/pytorch/examples/blob/4b119d735b802453479d739bf823f3f7d8d5d422/imagenet/main.py#L204-L214

**Comment by wangkuiyi** [comment]
The validation program that uses the above transformers

https://github.com/pytorch/examples/blob/4b119d735b802453479d739bf823f3f7d8d5d422/imagenet/main.py#L225-L230
