### ISSUE TITLE
Decoding jpg diff between Go image library and Python PIL library

### ISSUE THREAD

**Issue by QiJune** [wangkuiyi/gotorch#288]
I use the `ToTensor` transform to read the same image in GoTorch and PyTorch:

The last three Tensor value in GoTorch:
```
0.0788  0.0936  0.0936
```

In PyTorch:

```
0.0784, 0.0941, 0.0941
```

There is a little diff.

**Comment by QiJune** [comment]
Please refer to #303

**Comment by QiJune** [comment]
Here are two references: 

- https://stackoverflow.com/questions/44514897/difference-between-the-return-values-of-pil-image-open-and-tf-image-decode-jpeg
- https://stackoverflow.com/questions/44514897/difference-between-the-return-values-of-pil-image-open-and-tf-image-decode-jpeg

It seems that there are also differences between OpenCV, TensorFlow, and PIL.

> Well, this difference is arising from the fact that OpenCV, by default, uses integer accurate decompression of the JPEG image. In contrast, TensorFlow uses Discrete Cosine Transform as default.

**Comment by wangkuiyi** [comment]
It seems that such differences are inevitable. Let us close the issue as we cannot do anything with it.
