### ISSUE TITLE
Should we unify the build environment?

### ISSUE THREAD

**Issue by QiJune** [wangkuiyi/gotorch#70]
Recently, my two PRs work well on my local mac development environment but fail in CI.

In #60, I use clang-format to format the C++ codes in local already, but it fails the pre-commit checking in CI.

```log
$ pre-commit run -a
go fmt...................................................................Passed
go lint..................................................................Passed
validate toml........................................(no files to check)Skipped
Check files aren't using go's testing package........(no files to check)Skipped
cpplint..................................................................Passed
cppcheck.................................................................Passed
clang-format.............................................................Failed
- hook id: clang-format
- files were modified by this hook
```

In #64, I find that the macOS and Linux treat `int64_t` differently. In macOS, `in64_t` is `long long`, while `long` in Linux.

So, I have to write code `(*C.longlong)(unsafe.Pointer(&stride[0]))` in macOS, while `(*C.long)(unsafe.Pointer(&stride[0]))` in Linux. This introduce conditional compilation in go codes.

**Comment by wangkuiyi** [comment]
You should write 

```go
(*C.int64_t)(unsafe.Pointer(&stride[0]))
```
